# Generated by Django 3.2 on 2021-10-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='profiletype',
            table='profile_type',
        ),
    ]
