# Generated by Django 3.2 on 2021-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_my_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret_Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('s_key', models.CharField(max_length=300)),
                ('s_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'secret_key',
                'managed': True,
            },
        ),
    ]
